### ISSUE TITLE
[Bug] encoding issue

### ISSUE THREAD

**Issue by noraj** [pavanw3b/sh00t#10]
I openned a flag: **Application mapping results - XXE injection** and saw an encoding issue in the example payload given in the note:

![image](https://user-images.githubusercontent.com/16578570/50638706-0ca59a00-0f5f-11e9-9faa-26888911c6a8.png)

Maybe there is wrong encoding when the database is filled with `python reset.py` ?

Is `latin1` the right encoding to use?

https://github.com/pavanw3b/sh00t/blob/master/reset.py#L23

**Comment by pavanw3b** [comment]
Hey @noraj,
Thanks for spotting this. In other words, it's actually because of bad character copied to WAHH data file: https://github.com/pavanw3b/sh00t/blob/master/configuration/data/wahh.json#L513. Scroll right to spot it.

I've fixed it on my local. Will remote push to master soon. I'll also check if there are any more occurrences of these characters.

Thanks again!

**Comment by pavanw3b** [comment]
Commit https://github.com/pavanw3b/sh00t/commit/d768322491bcdee54a36e367663731c2059714f8 fixes this issue and some other occurrences of bad double & single quote chars in json data file.
Thanks for reporting.
